apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zxw7b86gk-go
  janus-idp.io/tekton: zxw7b86gk-go
  backstage.io/kubernetes-id: zxw7b86gk-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zxw7b86gk-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
